version: '3.9'
services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    ports:
      - "15051:25500"
    restart: always
   # Clash
  clash:
    image: dreamacro/clash:latest
    container_name: clash
    volumes:
      - ./configs/clash.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890/tcp"
      - "7890:7890/udp"
      - "9090:9090"
    depends_on:
      - subconverter
    restart: always

  clash-dashboard:
    image: centralx/clash-dashboard
    container_name: clash-dashboard
    ports:
      - "7880:80"
    depends_on:
      - clash
    restart: always

